name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RANDOM: "123456"
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest
        uses: bohn002/base64_encode_action@main
        with:
          env_name: "RANDOM"

      - name: Check outputs
        run: |
          echo "${{ steps.selftest.outputs.encoded_string }}"
          echo ${{ steps.selftest.outputs.encoded_string }} | base64 --decode